(define (lier)
  (let ((a (amb 1 2 3 4 5))
        (b (amb 1 2 3 4 5))
        (c (amb 1 2 3 4 5))
        (d (amb 1 2 3 4 5))
        (e (amb 1 2 3 4 5)))
    (require (xor (= d 2)
                  (= a 3)))
    (require (xor (= b 1)
                  (= c 2)))
    (require (xor (= c 3)
                  (= b 5)))
    (require (xor (= d 2)
                  (= e 4)))
    (require (xor (= e 4)
                  (= a 1)))
    (require (distinct? (list a b c d e)))
    (list a b c d e)))